### ISSUE TITLE
Log doesn't flush on unexpected failure

### ISSUE THREAD

**Issue by jonlin00** [cozis/blogtech#1]
As per title, `log_data` will happily log into it's internal buffer and, particularly in the usecase or `log_perror`, immediately exit.
Consequence: The most relevant error and why the server stopped is unavailable. Possibly even leaving an empty log file if socket initialization fails.
Potential fix: add `atexit(log_flush);` before the call to `socket`.

**Comment by cozis** [comment]
Yes, that's a problem. Apparently `atexit` is limited to [normal program terminations](https://man7.org/linux/man-pages/man3/atexit.3.html). It would be nice if we also managed to flush when crashing unexpectedly. I've never written a SIGSEGV handler so I'm missing the details

**Comment by jonlin00** [comment]
Should this tiny logger be expected to log even catastrophic failures? The simplest solution would probably be to `mmap` a crashlog file and to then write to it inside the signal handler. Of course during a graceful exit the crashlog should be deleted.
See here for additional detail regarding [async-signal-safe](https://man7.org/linux/man-pages/man7/signal-safety.7.html) functions and [here for sig_atomic_t](https://stackoverflow.com/questions/24931456/how-does-sig-atomic-t-actually-work).

**Comment by jonlin00** [comment]
On the topic of signal handlers.
```
bool stop = false;

void handle_sigterm(int signum) {
  (void)signum;
  stop = true;
}
```
Invokes undefined behaviour, stop should be changed from `bool stop` to `volatile sig_atomic_t stop`.

**Comment by cozis** [comment]
My idea was to change log_flush to be signal-safe and call that from handlers. In the mean time atexit should work. All calls to `abort` will need to be changed to `exit`  though

P.S. Thanks for the tip!

**Comment by cozis** [comment]
I just pushed these changes :)
