### ISSUE TITLE
Doesn't bind to port

### ISSUE THREAD

**Issue by yonas** [cozis/blogtech#8]
The program doesn't bind on any ports.

```sh
$ make
...
$ ./serve
```

```sh
$ lsof -i -n -P | grep 80
$
```

Similarly for `serve_debug` on port `8080`.

OS: `Ubuntu 24`

**Comment by cozis** [comment]
Are you running WSL? It seems WSL is unable to recognize listening sockets. Doing `curl 127.0.0.1` reaches the server just fine for me

**Comment by yonas** [comment]
@cozis No, I'm running regular Ubuntu.

**Comment by cozis** [comment]
So I'm assuming `curl` can't reach the server?

**Comment by yonas** [comment]
@cozis That's correct.

**Comment by cozis** [comment]
That's very strange. I tried `lsof -i -n -P | grep 80` on the VPS (Debian) and it works as expected.

Just to make sure the program is not stalling at initialization, can you run `strace ./serve_debug`? I just want to make sure the listener is being created.

Also let me know if there is other relevant information that could help

**Comment by yonas** [comment]
Thanks, that helped. The logs directory wasn't accessible.

I've submitted PR #9
